# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6bceceac9b8470b580905f4620aff1c2561ba590a74cd2aae3f24e42878fa619f79dbc2a143f431db012b6d341d529104280a1747ff42d8bf2d107c69fd4063

test:
  secret_key_base: d1497d757a3f1b39f7cf699027d37f1a3decaa8d4d5affc70a36033984d89adb5ea5d54cb339eb22409a73230e94a1c3191975e5e3be538150bf3f51d36df757

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
